baseURL = 'https://sangho0n.github.io/'
languageCode = 'ko-kr'
theme = 'hugo-theme-stack'
paginate = 5

copyright = "Sanghoon, Han"
disqusShortname = "hugo-theme-stack"
DefaultContentLanguage = "ko"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

[languages.ko]
contentDir = "content/ko"
languageName = "í•œêµ­ì–´"
title = "sanghoon's dev-log"
weight = 1

    [languages.ko.params]   
    description = "ê°œë°œì¼ì§€"
    mainSections = [ "post" ]
    featuredImageField = "image"
    rssFullContent = true
    
        [languages.ko.params.sidebar]
        emoji = "ğŸ˜€"
        subtitle = "ì•ˆë…•í•˜ì„¸ìš”. ê²Œì„ê°œë°œì í•œìƒí›ˆì…ë‹ˆë‹¤."
            [languages.ko.params.sidebar.avatar]
            enabled = true
            local = true
            src = 'avatar.png'
    
        [languages.ko.params.footer]
        since = 2023
        
        [languages.ko.params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"
        
        [languages.ko.params.article]
        math = false
        toc = true
        readingTime = false
        
        [languages.ko.params.article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"
        
        [languages.ko.params.comments]
        enabled = false
            provider = "disqus"
            [languages.ko.params.comments.disqusjs]
            
            [languages.ko.params.comments.utterances]
            issueTerm = "pathname"
            
            [languages.ko.params.comments.remark42]
            
            [languages.ko.params.comments.vssue]
            autoCreateIssue = false
            
            [languages.ko.params.comments.waline]
            emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
            requiredMeta = [ "name", "email", "url" ]
                [languages.ko.params.comments.waline.locale]
                admin = "Admin"
            
            [languages.ko.params.comments.twikoo]
            
            [languages.ko.params.comments.cactus]
            defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
            serverName = "cactus.chat"
            siteName = ""
            
            [languages.ko.params.comments.giscus]
            reactionsEnabled = 1
            emitMetadata = 0
            
            [languages.ko.params.comments.gitalk]
            
            [languages.ko.params.comments.cusdis]
        
        [[languages.ko.params.widgets.homepage]]
        type = "search"
        layout = "search"
        [[languages.ko.params.widgets.homepage]]
        type = "archives"
            [languages.ko.params.widgets.homepage.params]
            limit = 5
        [[languages.ko.params.widgets.homepage]]
        type = "categories"
            [languages.ko.params.widgets.homepage.params]
            limit = 10
            [[languages.ko.params.widgets.homepage]]
            type = "tag-cloud"
            [languages.ko.params.widgets.homepage.params]
            limit = 10
        [[languages.ko.params.widgets.page]]
        type = "toc"
        
        [languages.ko.params.opengraph.twitter]
        card = "summary_large_image"
        
        [languages.ko.params.defaultImage.opengraph]
        enabled = false
        local = false
        
        [languages.ko.params.colorScheme]
        toggle = true
        default = "auto"
        
        [languages.ko.params.imageProcessing.cover]
        enabled = true
        
        [languages.ko.params.imageProcessing.content]
        enabled = true
    
    [languages.ko.menu]
      [[languages.ko.menu.main]]
      identifier = "about"
      name = "About"
      url = "/ko/about/"
        [languages.ko.menu.main.params]
        icon = "user"
        
      [[languages.ko.menu.main]]
      identifier = "archives"
      name = "Archives"
      url = "/ko/archives/"
        [languages.ko.menu.main.params]
        icon = "archives"
    
      [[languages.ko.menu.social]]
      identifier = "github"
      name = "GitHub"
      url = "https://github.com/sangho0n"
    
        [languages.ko.menu.social.params]
        icon = "brand-github"
    
      [[languages.ko.menu.social]]
      identifier = "instagram"
      name = "Instagram"
      url = "https://www.instagram.com/sanghoon_eat/"
    
        [languages.ko.menu.social.params]
        icon = "brand-instagram"


[languages.en]
contentDir = "content/en"
languageName = "English"
title = "sanghoon's dev-log"
weight = 2

    [languages.en.params]   
    description = "dev-log"
    mainSections = [ "post" ]
    featuredImageField = "image"
    rssFullContent = true
    
        [languages.en.params.sidebar]
        emoji = "ğŸ˜€"
        subtitle = "Welcome to my blog!"
            [languages.en.params.sidebar.avatar]
            enabled = true
            local = true
            src = 'avatar.png'
    
        [languages.en.params.footer]
        since = 2023
        
        [languages.en.params.dateFormat]
        published = "Jan 02, 2006"
        lastUpdated = "Jan 02, 2006 15:04 MST"
        
        [languages.en.params.article]
        math = false
        toc = true
        readingTime = false
        
        [languages.en.params.article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"
        
        [languages.en.params.comments]
        enabled = false
            provider = "disqus"
            [languages.en.params.comments.disqusjs]
            
            [languages.en.params.comments.utterances]
            issueTerm = "pathname"
            
            [languages.en.params.comments.remark42]
            
            [languages.en.params.comments.vssue]
            autoCreateIssue = false
            
            [languages.en.params.comments.waline]
            emoji = [ "https://unpkg.com/@waline/emojis@1.0.1/weibo" ]
            requiredMeta = [ "name", "email", "url" ]
                [languages.en.params.comments.waline.locale]
                admin = "Admin"
            
            [languages.en.params.comments.twikoo]
            
            [languages.en.params.comments.cactus]
            defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
            serverName = "cactus.chat"
            siteName = ""
            
            [languages.en.params.comments.giscus]
            reactionsEnabled = 1
            emitMetadata = 0
            
            [languages.en.params.comments.gitalk]
            
            [languages.en.params.comments.cusdis]
        
        [[languages.en.params.widgets.homepage]]
        type = "search"
        layout = "search"
        [[languages.en.params.widgets.homepage]]
        type = "archives"
            [languages.en.params.widgets.homepage.params]
            limit = 5
        [[languages.en.params.widgets.homepage]]
        type = "categories"
            [languages.en.params.widgets.homepage.params]
            limit = 10
            [[languages.en.params.widgets.homepage]]
            type = "tag-cloud"
            [languages.en.params.widgets.homepage.params]
            limit = 10
        [[languages.en.params.widgets.page]]
        type = "toc"
        
        [languages.en.params.opengraph.twitter]
        card = "summary_large_image"
        
        [languages.en.params.defaultImage.opengraph]
        enabled = false
        local = false
        
        [languages.en.params.colorScheme]
        toggle = true
        default = "auto"
        
        [languages.en.params.imageProcessing.cover]
        enabled = true
        
        [languages.en.params.imageProcessing.content]
        enabled = true
            
    [languages.en.menu]
      [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/en/about/"
        [languages.en.menu.main.params]
        icon = "user"
        
      [[languages.en.menu.main]]
      identifier = "archives"
      name = "Archives"
      url = "/en/archives/"
        [languages.en.menu.main.params]
        icon = "archives"
    
      [[languages.en.menu.social]]
      identifier = "github"
      name = "GitHub"
      url = "https://github.com/sangho0n"
    
        [languages.en.menu.social.params]
        icon = "brand-github"
    
      [[languages.en.menu.social]]
      identifier = "instagram"
      name = "Instagram"
      url = "https://www.instagram.com/sanghoon_eat/"
    
        [languages.en.menu.social.params]
        icon = "brand-instagram"

        
[permalinks]
post = "/p/:slug/"
page = "/:slug/"

[related]
includeNewer = true
threshold = 60
toLower = false

  [[related.indices]]
  name = "tags"
  weight = 100

  [[related.indices]]
  name = "categories"
  weight = 200

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[markup.highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
